name: caller_app
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.11
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  cloud_firestore: ^4.4.5
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true