// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRBIKj0iMuhWIpzWN3pucXGR-XmSJ2MrM',
    appId: '1:1011962471566:web:42e154dc2090376e2f15df',
    messagingSenderId: '1011962471566',
    projectId: 'smartdoorbell-synectiks',
    authDomain: 'smartdoorbell-synectiks.firebaseapp.com',
    storageBucket: 'smartdoorbell-synectiks.firebasestorage.app',
    measurementId: 'G-5ZPQ0W4F32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPbPct13yWaPinowP-gQ7OlPM_ejwCIk',
    appId: '1:1011962471566:android:b4210d502902c5e72f15df',
    messagingSenderId: '1011962471566',
    projectId: 'smartdoorbell-synectiks',
    storageBucket: 'smartdoorbell-synectiks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5zhpQgx2HKPv6KHmKRgWZczEA_Qfx2w4',
    appId: '1:1011962471566:ios:5ef3c6bac97cd0722f15df',
    messagingSenderId: '1011962471566',
    projectId: 'smartdoorbell-synectiks',
    storageBucket: 'smartdoorbell-synectiks.firebasestorage.app',
    iosBundleId: 'com.example.caller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5zhpQgx2HKPv6KHmKRgWZczEA_Qfx2w4',
    appId: '1:1011962471566:ios:5ef3c6bac97cd0722f15df',
    messagingSenderId: '1011962471566',
    projectId: 'smartdoorbell-synectiks',
    storageBucket: 'smartdoorbell-synectiks.firebasestorage.app',
    iosBundleId: 'com.example.caller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRBIKj0iMuhWIpzWN3pucXGR-XmSJ2MrM',
    appId: '1:1011962471566:web:4c705b083131b2592f15df',
    messagingSenderId: '1011962471566',
    projectId: 'smartdoorbell-synectiks',
    authDomain: 'smartdoorbell-synectiks.firebaseapp.com',
    storageBucket: 'smartdoorbell-synectiks.firebasestorage.app',
    measurementId: 'G-FYM9BG9B5L',
  );
}
